# Generated by Django 5.1.8 on 2025-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("current_price", models.FloatField()),
                ("volume_today", models.BigIntegerField()),
                ("avg_volume", models.BigIntegerField(blank=True, null=True)),
                ("dvav", models.FloatField(blank=True, null=True)),
                ("dvsa", models.FloatField(blank=True, null=True)),
                ("pe_ratio", models.FloatField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("last_update", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
    ]
