# Generated by Django 5.1.8 on 2025-05-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockalert",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
